# Generated by Django 4.1.2 on 2023-01-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gorden ramseyex', max_length=100, verbose_name='Name')),
                ('image', models.ImageField(upload_to='chef')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='menu')),
                ('price', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('description', models.CharField(max_length=250)),
                ('people', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Klassyweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(upload_to='klassyweek')),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=1000)),
                ('category', models.CharField(default='dinner', max_length=100, verbose_name='Category')),
                ('chef', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.chef')),
            ],
        ),
    ]
