# Generated by Django 4.1.2 on 2023-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervation',
            name='surname',
        ),
        migrations.AddField(
            model_name='rezervation',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='rezervation',
            name='phoneNumber',
            field=models.IntegerField(default=1, verbose_name='phoneNumber'),
        ),
        migrations.AlterField(
            model_name='rezervation',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='rezervation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='rezervation',
            name='people',
            field=models.IntegerField(default=1, verbose_name='people'),
        ),
    ]
