# Generated by Django 4.1.4 on 2023-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_rezervation_surname_rezervation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervation',
            name='time',
            field=models.CharField(max_length=200, verbose_name='Time'),
        ),
    ]
