# Generated by Django 4.1.4 on 2023-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_rezervation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervation',
            name='date',
            field=models.CharField(max_length=200, verbose_name='Date'),
        ),
    ]
