# Generated by Django 4.1.4 on 2023-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_rezervation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name=' Ürün Adı')),
                ('product_img', models.CharField(max_length=150, verbose_name=' Ürün Resimi')),
                ('product_quantity', models.IntegerField(default=1, verbose_name='Ürün Adeti')),
                ('product_price', models.IntegerField(default=1, verbose_name='Ürün Fiyatı')),
            ],
        ),
    ]
